name: Github Pages Deploy 

on: 
  push: 
    branches: [main] 

jobs: 
  build:  
    runs-on: ubuntu-latest 

    steps:  
      - name: Checkout 
        uses: actions/checkout@v2.3.1
      - name: Use Node.js 16.x 
        uses: actions/setup-node@v1 
        with: 
          node-version: '16.13.0' 

      - name: Setup Yarn 
        uses: mskelton/setup-yarn@v1

      - name: Installing package dependencies 
        run: yarn install 


      - name: Defining the build cache 
        uses: actions/cache@v2 
        with: 
          path: | 
            ~/.npm 
            ${{ github.workspace }}/.next/cache 

          # generate a new cache whenever packages or source files change. 
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache 
          restore-keys: | 
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Build the App 
        run: yarn run build && yarn run export touch ./out/.nojekyll 

      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@v4.3.3 
        with: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          BRANCH: main 
          FOLDER: out